[tool.ruff]
line-length = 88
lint.extend-select = ["I"]  # enable isort-style import sorting
lint.ignore = ["E203", "E501"]  # black-compatible

[tool.isort]
profile = "black"

[tool.mypy]

[[tool.mypy.overrides]]
module = "graphviz.*"
ignore_missing_imports = true

