# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Install MySQL client dependencies (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -y default-libmysqlclient-dev

    - name: Set up virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        uv pip install ruff pytest mypy
        git submodule update --init --recursive
        uv pip install -e .
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: uv run ruff check .
    - name: Type check with mypy
      run: uv run mypy . --exclude www
    - name: Test with pytest
      run: uv run pytest
